### PR TITLE
Fix truncation with snprintf in buffer

### PR DESCRIPTION
**Pull request by ajscholl**
This should fix the following warnings (and errors, as -Werror is enabled):

```
netinet/sctp_indata.c: In function 'sctp_queue_data_to_stream':
netinet/sctp_indata.c:537:88: error: 'snprintf' output truncated before the last format character [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "Delivered MID=%8.8x, got TSN=%8.8x, SID=%4.4x, MID=%8.8x",
                                                                                        ^
netinet/sctp_indata.c:537:4: note: 'snprintf' output 65 bytes into a destination of size 64
    snprintf(msg, sizeof(msg), "Delivered MID=%8.8x, got TSN=%8.8x, SID=%4.4x, MID=%8.8x", strm->last_mid_delivered, control->sinfo_tsn, control->sinfo_stream, control->mid);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netinet/sctp_indata.c: In function 'sctp_process_a_data_chunk':
netinet/sctp_indata.c:1785:97: error: 'All fragments of a user message must be ordered or unordered (TSN=' directive output truncated writing 66 bytes into a region of size 64 [-Werror=format-truncation=]
     snprintf(msg, sizeof(msg), "All fragments of a user message must be ordered or unordered (TSN=%8.8x)",
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
netinet/sctp_indata.c:1785:5: note: 'snprintf' output 76 bytes into a destination of size 64
     snprintf(msg, sizeof(msg), "All fragments of a user message must be ordered or unordered (TSN=%8.8x)", tsn);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netinet/sctp_indata.c:1791:97: error: 'All fragments of a user message must be ordered or unordered (TSN=' directive output truncated writing 66 bytes into a region of size 64 [-Werror=format-truncation=]
     snprintf(msg, sizeof(msg), "All fragments of a user message must be ordered or unordered (TSN=%8.8x)",
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
netinet/sctp_indata.c:1791:5: note: 'snprintf' output 76 bytes into a destination of size 64
     snprintf(msg, sizeof(msg), "All fragments of a user message must be ordered or unordered (TSN=%8.8x)", tsn);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
netinet/sctp_indata.c:1908:88: error: 'snprintf' output truncated before the last format character [-Werror=format-truncation=]
    snprintf(msg, sizeof(msg), "Delivered MID=%8.8x, got TSN=%8.8x, SID=%4.4x, MID=%8.8x",
                                                                                        ^
netinet/sctp_indata.c:1908:4: note: 'snprintf' output 65 bytes into a destination of size 64
    snprintf(msg, sizeof(msg), "Delivered MID=%8.8x, got TSN=%8.8x, SID=%4.4x, MID=%8.8x", asoc->strmin[sid].last_mid_delivered, tsn, sid, mid);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by tuexen** [comment]
Hi,

I'm willing to take the truncation fix. The other stuff will go in separately, not in one merge.

Best regards
Michael

**Comment by ajscholl** [comment]
The other stuff was also not meant to be merged, seems like I did not quite understand that a pull-request gets updated if you commit something to your own repository.

**Comment by ajscholl** [comment]
Should be better now and I learned not to open pull-requests from master.

**Comment by tuexen** [comment]
Yepp, looks much better now. Will merge shortly.

**Pull request merged**
