### PR TITLE
Add mbedtls sha1 support

### PR DESCRIPTION
**Pull request by ycyang1229**
Hi, 
I added the mbedtls sha1 support. Hope this can help others use this lib with mbedtls.
thanks.

### CODE REVIEW

**Comment by tuexen** [comment]
@weinrank: OK with cmake related changes?

**Comment by ycyang1229** [comment]
> @weinrank: OK with cmake related changes?

Yes, I use cmake to build this change. Do I need to run any verifications?

**Comment by tuexen** [comment]
> > @weinrank: OK with cmake related changes?
> 
> Yes, I use cmake to build this change. Do I need to run any verifications?

No. But I have no experience with `cmake`, that is why I aking @weinrank to check it.

**Comment by ycyang1229** [comment]
> > > @weinrank: OK with cmake related changes?
> > 
> > 
> > Yes, I use cmake to build this change. Do I need to run any verifications?
> 
> No. But I have no experience with `cmake`, that is why I asking @weinrank to check it.
Big thanks. :)

**Comment by weinrank** [comment]
I'm fine with the cmake related changes. 👍

**Pull request merged**
