### PR TITLE
Enable GitHub actions to perform "sanity" compilatoin of new changes.

### PR DESCRIPTION
**Pull request by mstyura**
To avoid dummy issues with compilation, as introduced in #470 it might make sense to enable `GitHub Actions` on a repository to perform compilation on `Windows`, `Linux` and `Mac` on each incoming change to a `master` or PR. 
This is definitely not a full coverage of platforms, but at least it could detect the changes which breaks compilation on some of the platforms early enough and conveniently report compilation issue directly in `GitHub`.
This is no way a not a replacement of [an existing build bot from README.md](http://buildbot.nplab.de:18010/#/console), but rather a small addition to an existing bot.

### CODE REVIEW

**Comment by mstyura** [comment]
Dr. @tuexen, could you please have a look at this PR which should in some extent help early detection of changes breaking compilation? An example of `GitHub Actions` workflow execution can be seen here: https://github.com/mstyura/usrsctp/actions/runs/114793030.

**Comment by tuexen** [comment]
I'll leave that up to @weinrank. He is currently in charge of the buildbots.

**Comment by mstyura** [comment]
Hello @weinrank, could you please have a look at this PR?

**Comment by weinrank** [comment]
Hi @mstyura ,

I'm currently learning what GitHub Actions are and how they work.
In general, the idea of your PR looks good and it seems to be a good addition.

**Comment by tuexen** [comment]
@weinrank Lets me know what you think when you have learnt enough to say anything about this PR.

**Comment by mstyura** [comment]
Hello @weinrank 
Did you have a chance to have a deeper looks at this PR? I believe with latest addition of build matrix it could detect early an issue with IPV6 only builds which fixed recently in master.
Thanks a lot in advance!

**Comment by weinrank** [comment]
Hi @mstyura ,

I think your PR looks good and is a valuable addition. 👍

**Comment by mstyura** [comment]
@weinrank thanks! Could you please then merge this PR?

**Pull request merged**
