### PR TITLE
Ubuntu/Debian packaging

### PR DESCRIPTION
**Pull request by dreibh**
* CMake file improvements
* Ubuntu/Debian packaging
-> https://launchpad.net/~dreibh/+archive/ubuntu/ppa/+packages?field.name_filter=usrsctp&field.status_filter=published&field.series_filter=
-> https://mentors.debian.net/package/libusrsctp

### CODE REVIEW

**Comment by dreibh** [comment]
Made a few fixes.

**Comment by dreibh** [comment]
Merged with up-to-date "master" branch.

**Comment by dreibh** [comment]
Merged latest upstream version.

**Comment by linuxmaniac** [comment]
@dreibh I just filled the [ITP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864759) and I'm planing to work on this at [pkg-voip team repository](https://anonscm.debian.org/git/pkg-voip/libusrsctp.git/)

**Comment by dreibh** [comment]
This pull request is now integrated into Pull Request #117 .

**Pull request closed without merging**
