### PR TITLE
Fix BSD 3-clause license in source files.

### PR DESCRIPTION
**Pull request by taylor-b**
This makes the following changes:
* Updates 2-clause license to 3-clause license in all files that were
  still using 2-clause.
* Replaces "the name of Cisco Systems, Inc. and its contributors" and
  "the name of the University and its contributors" with "the name of
  the project and its contributors".
* Updates a couple files that were missing the license:
  fuzzer_fragments.c and programs_helper.c.

### CODE REVIEW

**Comment by tuexen** [comment]
> This makes the following changes:
> 
> * Updates 2-clause license to 3-clause license in all files that were
>   still using 2-clause.

Not sure why you think that 3-clause is the goal. I used the 2-clause license in all new files, since it is the preferred license of the FreeBSD project: https://www.freebsd.org/doc/en_US.ISO8859-1/articles/committers-guide/pref-license.html

> * Replaces "the name of Cisco Systems, Inc. and its contributors" and
>   "the name of the University and its contributors" with "the name of
>   the project and its contributors".

IANAL: Do you have an OK from Cisco Systems to do the removal?

> * Updates a couple files that were missing the license:
>   fuzzer_fragments.c and programs_helper.c.

Happy to take that, preferable by using the 2-clause license...

**Comment by taylor-b** [comment]
> Not sure why you think that 3-clause is the goal. I used the 2-clause license in all new files, since it is the preferred license of the FreeBSD project: https://www.freebsd.org/doc/en_US.ISO8859-1/articles/committers-guide/pref-license.html

This was mainly motivated by the fact that LICENSE.md uses the 3-clause license, and we have an automated tool that doesn't like the mismatch. But if the mismatch is intentional/unavoidable, I'll drop this.

> IANAL: Do you have an OK from Cisco Systems to do the removal? The University means UBC, I guess, since the port to userland was done by two grad students from UBC. One of them is working for Google, so you could check with him...

I haven't asked; I assumed that "the project and its contributors" would include Cisco/UBC since their copyrights are listed above. I can just undo those changes.

**Comment by tuexen** [comment]
> > Not sure why you think that 3-clause is the goal. I used the 2-clause license in all new files, since it is the preferred license of the FreeBSD project: https://www.freebsd.org/doc/en_US.ISO8859-1/articles/committers-guide/pref-license.html
> 
> This was mainly motivated by the fact that LICENSE.md uses the 3-clause license, and we have an automated tool that doesn't like the mismatch. But if the mismatch is intentional/unavoidable, I'll drop this.

The 3-clause and 2-clause license are used intentionally. The ones where Cisco was involved are 3-clause, newer ones are 2 clause and should be added as 2-clause.

> 
> > IANAL: Do you have an OK from Cisco Systems to do the removal? The University means UBC, I guess, since the port to userland was done by two grad students from UBC. One of them is working for Google, so you could check with him...
> 
> I haven't asked; I assumed that "the project and its contributors" would include Cisco/UBC since their copyrights are listed above. I can just undo those changes.

Please undo. The original authors are not with Cisco anymore, so there is no way to figure out if we can change the license. The text used is the one which were OK for Cisco at the time of writing the sources in the past.

**Comment by stewrtrs** [comment]
Bottom line is that  you *can not* change the license period end of story!!

R

> On Sep 16, 2020, at 4:48 PM, Michael Tüxen <notifications@github.com> wrote:
> 
> 
> Not sure why you think that 3-clause is the goal. I used the 2-clause license in all new files, since it is the preferred license of the FreeBSD project: https://www.freebsd.org/doc/en_US.ISO8859-1/articles/committers-guide/pref-license.html
> 
> This was mainly motivated by the fact that LICENSE.md uses the 3-clause license, and we have an automated tool that doesn't like the mismatch. But if the mismatch is intentional/unavoidable, I'll drop this.
> 
> The 3-clause and 2-clause license are used intentionally. The ones where Cisco was involved are 3-clause, newer ones are 2 clause and should be added as 2-clause.
> 
> IANAL: Do you have an OK from Cisco Systems to do the removal? The University means UBC, I guess, since the port to userland was done by two grad students from UBC. One of them is working for Google, so you could check with him...
> 
> I haven't asked; I assumed that "the project and its contributors" would include Cisco/UBC since their copyrights are listed above. I can just undo those changes.
> 
> Please undo. The original authors are not with Cisco anymore, so there is no way to figure out if we can change the license. The text used is the one which were OK for Cisco at the time of writing the sources in the past.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by taylor-b** [comment]
Understood, I'll just go ahead and close this.

**Comment by tuexen** [comment]
I took the typo fixes and added copyright statements where they were missing.

**Pull request closed without merging**
