### PR TITLE
Fix cross-build linux->mingw

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by tuexen** [comment]
@weinrank Can you check this doesn't break a native Windows build?

**Comment by orgads** [comment]
ping?

This cannot break Windows build, as Windows is case insensitive. I built the project on Windows, and it's fine.

**Comment by weinrank** [comment]
I've quickly checked the PR (configure & compile) and it looks good to me.

**Comment by tuexen** [comment]
> ping?
> 
> This cannot break Windows build, as Windows is case insensitive. I built the project on Windows, and it's fine.

Sorry. I was confused by the MSDN documentation, which sometimes use the first letter as a capital letter, but their examples do not... Thanks for the fix.

**Pull request merged**
