### PR TITLE
Unified version and soversion between all supported build systems

### LINKED ISSUE #561: New official release before Debian 11 freeze (needed for projects)
Hello the Team, @tuexen,

I wish you a Happy New Year!

It is possible to create a real new build instead of a git version?
The goal is to have the version before the Debian 11 freeze (2021-01-12).
- https://salsa.debian.org/pkg-voip-team/libusrsctp
cc @jonassmedegaard

It is used by several projects like Psi and Psi+.
- https://github.com/psi-im/psi/issues/607
- https://github.com/psi-im/iris/blob/master/CMakeLists.txt#L209

The last official version is very old, soon 5 years:
- 0.9.3.0 (8 Apr 2016)
- https://github.com/sctplab/usrsctp/releases

Thanks in advance.

### LINKED ISSUE #564: 0.9.4.0 changed the interface and didn't bump the SONAME
Depending packages require to be patched now, for example https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252581

Please always bump the shared library's soname when breaking API changes are made:
```
lib/libusrsctp.so.1
lib/libusrsctp.so.1.0.0
```
In this case 1 should be changed to 2.

### PR DESCRIPTION
**Pull request by xvitaly**
Unified version and soversion between all supported build systems.

Closes #564. Closes #561.

### CODE REVIEW

**Comment by xvitaly** [comment]
Now all build systems produces the same result.

Cmake:

```
$ ls -l
lrwxrwxrwx. 1 vitaly vitaly      15 Jan 13 14:01 libusrsctp.so -> libusrsctp.so.2
lrwxrwxrwx. 1 vitaly vitaly      19 Jan 13 14:01 libusrsctp.so.2 -> libusrsctp.so.2.0.0
-rwxrwxr-x. 1 vitaly vitaly 1801360 Jan 13 14:01 libusrsctp.so.2.0.0
```
```
$ objdump -p libusrsctp.so.2.0.0 | grep SONAME
  SONAME               libusrsctp.so.2
```

Meson:

```
$ ls -l
lrwxrwxrwx. 1 vitaly vitaly      15 Jan 13 14:02 libusrsctp.so -> libusrsctp.so.2
lrwxrwxrwx. 1 vitaly vitaly      19 Jan 13 14:02 libusrsctp.so.2 -> libusrsctp.so.2.0.0
-rwxrwxr-x. 1 vitaly vitaly 1731888 Jan 13 14:03 libusrsctp.so.2.0.0
```
```
$ objdump -p libusrsctp.so.2.0.0 | grep SONAME
  SONAME               libusrsctp.so.2
```

Automake:

```
$ ls -l
lrwxrwxrwx. 1 vitaly vitaly      19 Jan 13 14:04 libusrsctp.so -> libusrsctp.so.2.0.0
lrwxrwxrwx. 1 vitaly vitaly      19 Jan 13 14:04 libusrsctp.so.2 -> libusrsctp.so.2.0.0
-rwxr-xr-x. 1 vitaly vitaly 1798720 Jan 13 14:04 libusrsctp.so.2.0.0
```

```
$ objdump -p libusrsctp.so.2.0.0 | grep SONAME
  SONAME               libusrsctp.so.2
```

**Comment by tehnick** [comment]
LGTM

**Comment by tuexen** [comment]
@weinrank. @lgrahl OK?

**Comment by tuexen** [comment]
Thanks for the help!

**Comment by xvitaly** [comment]
@tuexen Can you make a new tag 0.9.5.0?

**Comment by tuexen** [comment]
> On 13. Jan 2021, at 15:45, Vitaly Zaitsev <notifications@github.com> wrote:
> 
> 
> @tuexen Can you make a new tag 0.9.5.0?
Done.

**Comment by xvitaly** [comment]
> Done.

Thanks. Will update Fedora builds soon.

**Pull request merged**
