### PR TITLE
MinGW cross compile correction

### PR DESCRIPTION
**Pull request by CoolmanCZ**

### CODE REVIEW

**Comment by tuexen** [comment]
@weinrank: OK?

**Comment by weinrank** [comment]
@CoolmanCZ can you provide a bit more information about this issue?

**Comment by CoolmanCZ** [comment]
Hi,
The problem is the with the first capital letter. The library name in the linux (e.g. Ubuntu) using lowercase letters only.

**Comment by weinrank** [comment]
Okay, since Windows is incasesensitive : 👍🏻

**Pull request merged**
