### PR TITLE
Fix crash with HTCP

### PR DESCRIPTION
**Pull request by nxrighthere**
Fixes https://github.com/sctplab/usrsctp/issues/395

### CODE REVIEW

**Comment by lgrahl** [comment]
Ran into the same issue and applied the patch successfully.

**Comment by ghazel** [comment]
Same here.

**Comment by saurik** [comment]
@tuexen Yo! Just in case, I thought I'd directly ping you; there seems to be four people (I'm working with @ghazel, and so don't count as another person myself, but there are three in this thread and one in the referenced issue) who have experienced the same bug and are saying this patch works... what is the best way to help get this change committed?

**Comment by tuexen** [comment]
The reason I was hesitating to commit this, is that the CC is not tested very well and the corresponding CC for TCP implemented in [cc_htcp.c](https://svnweb.freebsd.org/base/head/sys/netinet/cc/cc_htcp.c) seems to be different. It is based on an individual submission ([draft-leith-tcp-htcp-06.txt](https://tools.ietf.org/html/draft-leith-tcp-htcp-06)) and I'm not sure why it wasn't adopted in a WG and further developed to an RFC.

However, this pull requested avoids a division by zero bug, so it is better what was there before.

**Pull request merged**
